const productEntries = [
    {
        id: "hamper-Lavender Lux Hamper",
        name: "Lavender Lux Hamper",
        price: 2999,
        image: "Website_Images/Lavender Lux 3.jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-Lavender Lux Hamper (Angle 2)",
        name: "Lavender Lux Hamper (Angle 2)",
        price: 2999,
        image: "Website_Images/Lavender Lux 2.jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-Lavender Lux Hamper (Angle 3)",
        name: "Lavender Lux Hamper (Angle 3)",
        price: 2999,
        image: "Website_Images/Lavender Lux.jpeg",
        category: "Signature Big Hampers",
    },  
    {
        id: "hamper-Jelly bangles 1 dozen",
        name: "Jelly bangles 1 dozen",
        price: 149,
        image: "Website_Images/Jelly 1.jpeg",
        category: "Jewellery",
  },
  {
        id: "hamper-Jelly bangles 1 dozen",
        name: "Jelly bangles 1 dozen",
        price: 149,
        image: "Website_Images/Jelly 2.jpeg",
        category: "Jewellery",
  },
  {
     id: "hamper-Jelly bangles 1 dozen",
     name: "Jelly bangles 1 dozen",
     price: 149,
     image: "Website_Images/Jelly 3.jpeg",
     category: "Jewellery",
  },
  {
    id: "hamper-Jelly bangles 1 dozen",
    name: "Jelly bangles 1 dozen",
    price: 149,
    image: "Website_Images/Jelly 4.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-Jelly bangles 1 dozen",
    name: "Jelly bangles 1 dozen",
    price: 149,
    image: "Website_Images/Jelly 5.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-Jelly bangles 1 dozen",
    name: "Jelly bangles 1 dozen",
    price: 149,
    image: "Website_Images/Jelly 6.jpeg",
    category: "Jewellery",
  },
    {
        id: "hamper-bb-1",
        name: "Blue Big Hamper",
        price: 999,
        image: "Website_Images/Big Blue New (Angle 1).jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-bb-2",
        name: "Blue Big Hamper (Angle 2)",
        price: 999,
        image: "Website_Images/Big Blue New (Angle 2).jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-bb-3",
        name: "Blue Big Hamper (Angle 3)",
        price: 999,
        image: "Website_Images/Big Blue New (Angle 3).jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-bb-4",
        name: "Blue Big Hamper (Angle 4)",
        price: 999,
        image: "Website_Images/Big Blue New (Angle 4).jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-bp-1",
        name: "Pink big hamper",
        price: 999,
       image: "Website_Images/Pink big hamper angle 11.jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-bp-2",
        name: "Pink big hamper (Angle 2)",
        price: 999,
        image: "Website_Images/Big Pink New (Angle 2).jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-bp-3",
        name: "Pink big hamper (Angle 3)",
        price: 999,
        image: "Website_Images/Big Pink New (Angle 3).jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-bp-4",
        name: "Pink big hamper (Angle 4)",
        price: 999,
        image: "Website_Images/Big Pink New (Angle 4).jpeg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-01",
        name: "Luxury Blue Hamper",
        price: 1499,
        image: "Website_Images/Big Blue Hamper (1).jpg",
        category: "Signature Big Hampers",
        featured: true,
    },
    {
        id: "hamper-02",
        name: "Luxury Blue Hamper (Angle 2)",
        price: 1499,
        image: "Website_Images/Big Blue Hamper.jpg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-03",
        name: "Luxury Pink Hamper",
        price: 1999,
        image: "Website_Images/Big Pink Hamper (1).jpg",
        category: "Signature Big Hampers",
        featured: true,
    },
    {
        id: "hamper-04",
        name: "Luxury Pink Hamper (Angle 2)",
        price: 1999,
        image: "Website_Images/Big Pink Hamper.jpg",
        category: "Signature Big Hampers",
    },
    {
        id: "hamper-05",
        name: "Handmade Red Rose",
        price: 199,
        image: "Website_Images/Handmade Red Rose.jpg",
        category: "Bouquets & Roses",
        featured: true,
    },
    {
        id: "hamper-06",
        name: "Munch Bunch",
        price: 299,
        image: "Website_Images/Munch Bunch.jpg",
        category: "Occasion Hampers",
    },
    {
        id: "hamper-07",
        name: "Pink White Rose Bouquet",
        price: 899,
        image: "Website_Images/Pink White Rose Bouquet.jpg",
        category: "Bouquets & Roses",
    },
    {
        id: "hamper-08",
        name: "Polaroids 5 Star Bouquet",
        price: 1499,
        image: "Website_Images/Polaroids 5 Star Bouquet.jpg",
        category: "Bouquets & Roses",
        featured: true,
    },
    {
        id: "hamper-09",
        name: "Polaroids 5 Star Bouquet (Angle 2)",
        price: 1499,
        image: "Website_Images/Polaroids 5 Star Bouquet (1).jpg",
        category: " Bouquets & Roses",
    },
    {
        id: "hamper-10",
        name: "Polaroids 5 Star Bouquet (Angle 3)",
        price: 1499,
        image: "Website_Images/Polaroids 5 star bouquet (2).jpg",
        category: "Bouquets & Roses",
    },
    {
        id: "hamper-11",
        name: "Polaroids",
        price: 99,
        image: "Website_Images/Polaroids.jpg",
        category: "Polaroid Gifts",
    },
    {
        id: "hamper-12",
        name: "Sorry Hamper",
        price: 399,
        image: "Website_Images/Sorry Hamper (1).jpg",
        category: "Occasion Hampers",
    },
    {
        id: "hamper-13",
        name: "Sorry Hamper (Angle 2)",
        price: 399,
        image: "Website_Images/Sorry Hamper (2).jpg",
        category: "Occasion Hampers",
    },
    {
        id: "hamper-14",
        name: "Valentine's Big Box Chocolate Hamper",
        price: 699,
        image: "Website_Images/Valentine's Big Box Chocolate Hamper.jpg",
        category: "Valentine's Collection",
        featured: true,
    },
    {
        id: "hamper-15",
        name: "Valentine's Big Hamper",
        price: 999,
        image: "Website_Images/Valentine's Big Hamper (1).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-16",
        name: "Valentine's Big Hamper (Angle 2)",
        price: 999,
        image: "Website_Images/Valentine's Big Hamper (2).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-17",
        name: "Valentine's Card Hamper",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper.jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-18",
        name: "Valentine's Card Hamper (Angle 1)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (1).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-19",
        name: "Valentine's Card Hamper (Angle 2)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (2).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-20",
        name: "Valentine's Card Hamper (Angle 3)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (3).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-21",
        name: "Valentine's Card Hamper (Angle 4)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (4).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-22",
        name: "Valentine's Card Hamper (Angle 5)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (5).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-23",
        name: "Valentine's Card Hamper (Angle 6)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (6).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-24",
        name: "Valentine's Card Hamper (Angle 7)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (7).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-25",
        name: "Valentine's Card Hamper (Angle 8)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (8).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-26",
        name: "Valentine's Card Hamper (Angle 9)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (9).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-27",
        name: "Valentine's Card Hamper (Angle 10)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (10).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-28",
        name: "Valentine's Card Hamper (Angle 12)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (12).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-29",
        name: "Valentine's Card Hamper (Angle 13)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (13).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-30",
        name: "Valentine's Card Hamper (Angle 14)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (14).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-31",
        name: "Valentine's Card Hamper (Angle 15)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (15).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-32",
        name: "Valentine's Card Hamper (Angle 16)",
        price: 799,
        image: "Website_Images/Valentine's Card Hamper (16).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-33",
        name: "Valentine's Chocolate Hamper (with lights)",
        price: 349,
        image: "Website_Images/Valentine's Chocolate Hamper (with lights).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-34",
        name: "Valentine's Chocolate Hamper (with lights) (Angle 2)",
        price: 349,
        image: "Website_Images/Valentine's Chocolate Hamper (with lights) (2).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-35",
        name: "Valentine's Small Chocolate Hamper (with polaroids)",
        price: 349,
        image: "Website_Images/Valentine's small Chocolate Hamper (with polaroids).jpg",
        category: "Valentine's Collection",
    },
    {
        id: "hamper-36",
        name: "Valentine's Small Hamper (with Teddy)",
        price: 399,
        image: "Website_Images/Valentine's small Hamper (with Teddy).jpg",
        category: "Valentine's Collection",
    },
  {
    id: "hamper-aaa-01",
    name: "52 raindrop and ghonghroo Kashmiri bangles 🪞🦢",
    price: 1349,
    description: "Description- 4 dozen different color bagles and 4 ghoonghroo bangles total 52 bangles with lights 🌸✨",
    image: "Website_Images/52-raindrop-and-ghonghroo-kashmiri-bangles 5.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-aaa-02",
    name: "52 raindrop and ghonghroo Kashmiri bangles 🪞🦢 (Angle 2)",
    price: 1349,
    description: "Description- 4 dozen different color bagles and 4 ghoonghroo bangles total 52 bangles with lights 🌸✨",
    image: "Website_Images/52-raindrop-and-ghonghroo-kashmiri-bangles 2.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-aaa-03",
    name: "52 raindrop and ghonghroo Kashmiri bangles 🪞🦢 (Angle 3)",
    price: 1349,
    description: "Description- 4 dozen different color bagles and 4 ghoonghroo bangles total 52 bangles with lights 🌸✨",
    image: "Website_Images/52-raindrop-and-ghonghroo-kashmiri-bangles 3.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-aaa-04",
    name: "52 raindrop and ghonghroo Kashmiri bangles 🪞🦢 (Angle 4)",
    price: 1349,
    description: "Description- 4 dozen different color bagles and 4 ghoonghroo bangles total 52 bangles with lights 🌸✨",
    image: "Website_Images/52-raindrop-and-ghonghroo-kashmiri-bangles 4.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-bbb-01",
    name: "60 raindrop bangle box (Angle 1)",
    price: 1499,
    description: "Description- 60 rain drop bagels 12 bangles in 5 different Colors 6 ghoonghroo bangles - including lights in box.",
    image: "Website_Images/60 raindrop bangle box (2).jpeg",
    category: "Jewellery",
  },
  
  {
    id: "hamper-bbb-02",
    name: "60 raindrop bangle box (Angle 2)",
    price: 1499, 
    description: "Description- 60 rain drop bagels 12 bangles in 5 different Colors 6 ghoonghroo bangles - including lights in box.",
    image: "Website_Images/60 raindrop bangle box (3).jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-bbb-03",
    name: "60 raindrop bangle box (Angle 3)",
    price: 1499,
    description: "Description- 60 rain drop bagels 12 bangles in 5 different Colors 6 ghoonghroo bangles - including lights in box.",
    image: "Website_Images/60 raindrop bangle box.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-00",
    name: "12 raindrop bangle and 4 ghunghroo bangle ✨🪞",
    price: 399,
    description: "Description- 12 raindrop bangles and 4 ghoonghroo bangles Please write color of the bangles (if any) on note after checking out your cart or WhatsApp us on 9266857606 with order id",
    image: "Website_Images/12 raindrop bangle and 4 ghunghroo bangle.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-00-1",
    name: "12 raindrop bangle and 4 ghunghroo bangle ✨🪞 (Angle 2)",
    price: 399,
    description: "Description- 12 raindrop bangles and 4 ghoonghroo bangles Please write color of the bangles (if any) on note after checking out your cart or WhatsApp us on 9266857606 with order id",
    image: "Website_Images/12 raindrop bangle and 4 ghunghroo bangle 2.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-00-2",
    name: "12 raindrop bangle and 4 ghunghroo bangle ✨🪞 (Angle 3)",
    price: 399,
    description: "Description- 12 raindrop bangles and 4 ghoonghroo bangles Please write color of the bangles (if any) on note after checking out your cart or WhatsApp us on 9266857606 with order id",
    image: "Website_Images/12 raindrop bangle and 4 ghunghroo bangle 3.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-00-3",
    name: "12 raindrop bangle and 4 ghunghroo bangle ✨🪞 (Angle 4)",
    price: 399,
    description: "Description- 12 raindrop bangles and 4 ghoonghroo bangles Please write color of the bangles (if any) on note after checking out your cart or WhatsApp us on 9266857606 with order id",
    image: "Website_Images/12 raindrop bangle and 4 ghunghroo bangle 4.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-00-4",
    name: "12 raindrop bangle and 4 ghunghroo bangle ✨🪞 (Angle 5)",
    price: 399,
    description: "Description- 12 raindrop bangles and 4 ghoonghroo bangles Please write color of the bangles (if any) on note after checking out your cart or WhatsApp us on 9266857606 with order id",
    image: "Website_Images/12 raindrop bangle and 4 ghunghroo bangle 5.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-00-5",
    name: "12 raindrop bangle and 4 ghunghroo bangle ✨🪞 (Angle 6)",
    price: 399,
    description: "Description- 12 raindrop bangles and 4 ghoonghroo bangles Please write color of the bangles (if any) on note after checking out your cart or WhatsApp us on 9266857606 with order id",
    image: "Website_Images/12 raindrop bangle and 4 ghunghroo bangle 6.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-00-6",
    name: "12 raindrop bangle and 4 ghunghroo bangle ✨🪞 (Angle 7)",
    price: 399,
    description: "Description- 12 raindrop bangles and 4 ghoonghroo bangles Please write color of the bangles (if any) on note after checking out your cart or WhatsApp us on 9266857606 with order id",
    image: "Website_Images/12 raindrop bangle and 4 ghunghroo bangle 7.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-00-7",
    name: "12 raindrop bangle and 4 ghunghroo bangle ✨🪞 (Angle 8)",
    price: 399,
    description: "Description- 12 raindrop bangles and 4 ghoonghroo bangles Please write color of the bangles (if any) on note after checking out your cart or WhatsApp us on 9266857606 with order id",
    image: "Website_Images/12 raindrop bangle and 4 ghunghroo bangle 8.jpeg",
    category: "Jewellery",
  }, 
  {
    id: "hamper-Jelly bangles",
    name: "Jelly bangles",
    price: 199,
    image: "Website_Images/Jelly Bangles.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-Jelly bangles",
    name: "Jelly bangles (Angle 2)",
    price: 199,
    image: "Website_Images/Jelly Bangles 2.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-Jelly bangles",
    name: "Jelly bangles (Angle 3)",
    price: 199,
    image: "Website_Images/Jelly Bangles 3.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-Jelly bangles",
    name: "Jelly bangles (Angle 4)",
    price: 199,
    image: "Website_Images/Jelly Bangles 4.jpeg",
    category: "Jewellery",
  },
   {
    id: "hamper-bc-1",
    name: "Empty Bangle box ",
    price: 399,
    description: " size - 30x12x8 cm Please with color preference ( pink or golden ) on note after checking out your note or WhatsApp us on 9266857606 with your order id",
    image: "Website_Images/Empty Bangle box.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-bc-2",
    name: "Empty Bangle box (angle 1)",
    price: 399,
    description: " size - 30x12x8 cm Please with color preference ( pink or golden ) on note after checking out your note or WhatsApp us on 9266857606 with your order id",
    image: "Website_Images/Empty Bangle box 2.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-bb-2",
    name: "Big Blue Hamper (Angle 2)",
    price: 999,
    image: "Website_Images/Big Blue New (Angle 2).jpeg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-bb-3",
    name: "Big Blue Hamper (Angle 3)",
    price: 999,
    image: "Website_Images/Big Blue New (Angle 3).jpeg",
    category: "Signature Big Hampers",
  },
  
  {
    id: "hamper-bp-1",
    name: "Pink big hamper",
    price: 999,
    description: "It’s contain 12 pink items Things may vary on availability We will provide you more than mentioned but we can’t guarantee exact things … but we will try our best to satisfy your need as we send you a video before dispatching so you can make changes in your order ❤️",
    image: "Website_Images/Big Pink New (Angle 1).jpeg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-bp-2",
    name: "Pink big hamper (Angle 2)",
    price: 999,
    image: "Website_Images/Big Pink New (Angle 2).jpeg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-bp-3",
    name: "Pink big hamper (Angle 3)",
    price: 999,
    image: "Website_Images/Big Pink New (Angle 3).jpeg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-bp-4",
    name: "Pink big hamper (Angle 4)",
    price: 999,
    image: "Website_Images/Big Pink New (Angle 4).jpeg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-01",
    name: "Luxury Blue Hamper",
    price: 1499,
    description: "Premium quality box containing 12 blue items. Things may vary on availability — we will provide you more than mentioned but we can't guarantee exact things, but we will try our best to satisfy your needs.",
    image: "Website_Images/Big Blue Hamper (1).jpg",
    category: "Signature Big Hampers",
    
  },
  {
    id: "hamper-02",
    name: "Luxury Blue Hamper (Angle 2)",
    price: 1499,
    image: "Website_Images/Big Blue Hamper.jpg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-02b",
    name: "Luxury Blue Hamper (Angle 3)",
    price: 1499,
    image: "Website_Images/Big Blue Hamper (2).jpg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-03",
    name: "Luxury Pink Hamper",
    price: 1999,
    description: "Premium quality box containing 12 luxury pink items. Things may vary on availability — we will provide you more than mentioned but we can't guarantee exact things, but we will try our best to satisfy your needs.",
    image: "Website_Images/Big Pink Hamper (1).jpg",
    category: "Signature Big Hampers",
    
  },
  {
    id: "hamper-04",
    name: "Luxury Pink Hamper (Angle 2)",
    price: 1999,
    image: "Website_Images/Big Pink Hamper.jpg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-04b",
    name: "Luxury Pink Hamper (Angle 3)",
    price: 1999,
    image: "Website_Images/Big Pink Hamper (3).jpg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-04c",
    name: "Luxury Pink Hamper (Angle 4)",
    price: 1999,
    image: "Website_Images/Big Pink Hamper (4).jpg",
    category: "Signature Big Hampers",
  },
  {
    id: "hamper-05",
    name: "Handmade Red Rose",
    price: 199,
    description: "Handcrafted rose made from satin ribbon. Colors available. Perfect for romantic gestures or as a keepsake gift.",
    image: "Website_Images/Handmade Red Rose.jpg",
    category: "Bouquets & Roses",
    
  },
  {
    id: "hamper-rose-4",
    name: "4 Handmade Rose Bouquet",
    price: 899,
    description: "Beautiful bouquet of 4 handmade roses made from satin ribbon. Colors available. A perfect romantic gift.",
    image: "Website_Images/Pink White Rose Bouquet.jpg",
    category: "Bouquets & Roses",
    
  },
  {
    id: "hamper-rrr-1",
    name: "Black Clover Stainless Steel Bracelet",
    price: 189,
    description: "Stylish black clover bracelet made from stainless steel. A trendy accessory for any occasion.",
    image: "Website_Images/Black Clover Stainless Steel Bracelet.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-rrr-2",
    name: "Black Clover Stainless Steel Bracelet (Angle 2)",
    price: 189,
    description: "Stylish black clover bracelet made from stainless steel. A trendy accessory for any occasion.",
    image: "Website_Images/Black Clover Stainless Steel Bracelet (2).jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-ddd-1",
    name: "Rose Themed Gold Plated Anti Tarnish Pendant",
    price: 199,
    description: "✨ Elegant Floral Pendant Design: Stylish gold plated necklace for woman / for daily wear.",
    image: "Website_Images/rose-themed-gold-plated-anti-tarnish-pendant.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-ddd-2",
    name: "Rose Themed Gold Plated Anti Tarnish Pendant(Angle 2)",
    price: 199,
    description: "✨ Elegant Floral Pendant Design: Stylish gold plated necklace for woman / for daily wear.",
    image: "Website_Images/rose-themed-gold-plated-anti-tarnish-pendant-2.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-vvv-1",
    name: "Heart Gold Plated Anti Tarnish Pendant",
    price: 199,
    description: "Anti tarnish / gold plated, for daily wear use",
    image: "Website_Images/heart-gold-plated-anti-tarnish-pendant.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-vvv-2",
    name: "Heart Gold Plated Anti Tarnish Pendant(Angle 2)",
    price: 199,
    description: "Anti tarnish / gold plated, for daily wear use",
    image: "Website_Images/heart-gold-plated-anti-tarnish-pendant-2.jpeg",
    category: "Jewellery",
  },
  {
    id: "hamper-06",
    name: "Munch Bunch",
    price: 299,
    description: "A fun snack-forward chocolate hamper with a variety of chocolates. Great for birthdays and surprises.",
    image: "Website_Images/Munch Bunch.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-08",
    name: "Polaroids 5 Star Bouquet",
    price: 1499,
    description: "A stunning bouquet featuring 6-7 polaroids and 10-11 five star chocolates. Fragile item — difficult to deliver far.",
    image: "Website_Images/Polaroids 5 Star Bouquet.jpg",
    category: "Polaroid Gifts",
    
  },
  {
    id: "hamper-09",
    name: "Polaroids 5 Star Bouquet (Angle 2)",
    price: 1499,
    image: "Website_Images/Polaroids 5 Star Bouquet (1).jpg",
    category: "Polaroid Gifts",
  },
  {
    id: "hamper-10",
    name: "Polaroids 5 Star Bouquet (Angle 3)",
    price: 1499,
    image: "Website_Images/Polaroids 5 star bouquet (2).jpg",
    category: "Polaroid Gifts",
  },
  {
    id: "hamper-polaroid-choc",
    name: "Polaroid Chocolate Hamper",
    price: 1499,
    description: "A unique hamper combining polaroid memories with premium chocolates. Makes for a wonderful personalised gift.",
    image: "Website_Images/Polaroid Chocolate Hamper.jpg",
    category: "Polaroid Gifts",
    
  },
  {
    id: "hamper-11",
    name: "Polaroids",
    price: 99,
    description: "Cute polaroid prints — a keepsake gift to cherish memories forever.",
    image: "Website_Images/Polaroids.jpg",
    category: "Polaroid Gifts",
  },
  {
    id: "hamper-12",
    name: "Sorry Hamper",
    price: 399,
    description: "Apology hamper with comfort picks and a heartfelt note. Say sorry in style.",
    image: "Website_Images/Sorry Hamper (1).jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-13",
    name: "Sorry Hamper (Angle 2)",
    price: 399,
    image: "Website_Images/Sorry Hamper (2).jpg",
    category: "Occasion Hampers",
  },
  // ── New Hampers ──
  {
    id: "hamper-chocolate-sq",
    name: "Chocolate Square Hamper",
    price: 599,
    description: "A delightful chocolate box containing 2 gold chocolates, 4 five stars, 4 Kit Kats and 2 Dairy Milks.",
    image: "Website_Images/Chocolate Square Hamper.jpg",
    category: "Occasion Hampers",
    
  },
  {
    id: "hamper-choc-jhumka",
    name: "Chocolate Hamper + Jhumka",
    price: 599,
    description: "5-6 chocolate cards paired with 3 beautiful pairs of jhumkas. A sweet and stylish gift combo.",
    image: "Website_Images/Chocolate Hamper Jhumka.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-choc-jhumka-2",
    name: "Chocolate Hamper + Jhumka (Angle 2)",
    price: 599,
    image: "Website_Images/Chocolate Hamper Jhumka (2).jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-small-choc",
    name: "Chocolate Hamper",
    price: 299,
    description: "Compact chocolate hamper with 5-6 chocolate cards — perfect for a sweet surprise.",
    image: "Website_Images/Small Chocolate Hamper.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-bitcoin-lights",
    name: "Big Chocolate Hamper + Lights",
    price: 599,
    description: "Premium big box with lights containing 10 chocolate cards. A glowing gift that stands out!",
    image: "Website_Images/Valentine's Big Box Chocolate Hamper.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-lit",
    name: "Lit Hamper 🔥",
    price: 999,
    description: "3 medium claw clips, 3 small claw clips, 2 satin scrunchies, 1 necklace, 1 pair of earrings, 1 Kinder Joy, 4-5 polaroids, 4-5 quotes and a happy birthday greeting.",
    image: "Website_Images/Lit Hamper.png",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-lit-2",
    name: "Lit Hamper 🔥 (Angle 2)",
    price: 999,
    image: "Website_Images/Lit Hamper (2).jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-lit-3",
    name: "Lit Hamper 🔥 (Angle 3)",
    price: 999,
    image: "Website_Images/Lit Hamper (3).jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-birthday-pink",
    name: "Birthday Pink Hamper",
    price: 999,
    description: "This hamper contains 12 items. Things may vary on availability — we will provide more than 12 but can't guarantee exact things. We send a video before dispatching so you can make changes.",
    image: "Website_Images/Birthday Pink Hamper.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-tennie",
    name: "Tennie Hamper",
    price: 799,
    description: "This hamper contains 10 items. Things may vary on availability — we will provide more than 10 but can't guarantee exact things. We send a video before dispatching so you can make changes.",
    image: "Website_Images/Tennie Hamper.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-boom-pink",
    name: "Boom Pink Hamper",
    price: 499,
    description: "This hamper contains 6 items. Things may vary on availability — we will provide more than 6 but can't guarantee exact things. We send you a video before dispatching so you can make changes.",
    image: "Website_Images/Boom Pink Hamper.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-boom-pink-2",
    name: "Boom Pink Hamper (Angle 2)",
    price: 499,
    image: "Website_Images/Boom Pink Hamper (2).jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-eightieee",
    name: "Eightiee Jewel Hamper",
    price: 699,
    description: "8 beautiful jewels: 2 necklaces, 2 jhumkas, 2 studs and 2 bracelets. Perfect for the jewellery lover.",
    image: "Website_Images/Eightieee Hamper.jpg",
    category: "Occasion Hampers",
    
  },
  {
    id: "hamper-batman",
    name: "Batman Hamper",
    price: 1499,
    description: "Batman big letter with customisation, Batman mug, Batman action figure, Batman keychain and some chocolates. Perfect for Batman fans!",
    image: "Website_Images/Batman Hamper.jpg",
    category: "Occasion Hampers",
    
  },
  {
    id: "hamper-batman-2",
    name: "Batman Hamper (Angle 2)",
    price: 1499,
    image: "Website_Images/Batman Hamper (2).jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-blue-small",
    name: "Blue Hamper (Small)",
    price: 599,
    description: "Cute small blue hamper containing 11-12 blue items. Items depend on availability.",
    image: "Website_Images/Blue Hamper Small.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-green-small",
    name: "Green Hamper (Small)",
    price: 599,
    description: "Cute small green hamper containing 11-12 green items. Items depend on availability.",
    image: "Website_Images/Green Hamper Small.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-pink-lippie",
    name: "Small Pink Lippie Hamper",
    price: 299,
    description: "A cute pink gift set with a pink lip gloss, pink keychain and a pair of earrings.",
    image: "Website_Images/Small Pink Lippie Hamper.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-pink-lippie-3",
    name: "Small Pink Lippie Hamper (Angle 2)",
    price: 299,
    image: "Website_Images/Pink Lippie Hamper (3).jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-blue-lippie",
    name: "Small Blue Lippie Hamper",
    price: 299,
    description: "A cute blue gift set with a blue lip gloss, blue keychain and a pair of earrings.",
    image: "Website_Images/Small Blue Lippie Hamper.jpg",
    category: "Occasion Hampers",
  },
  {
    id: "hamper-small-lippie",
    name: "Small Lippie Hamper",
    price: 299,
    description: "A mini lip gloss hamper — great as a small treat or add-on gift.",
    image: "Website_Images/Small Lippie Hamper.jpg",
    category: "Occasion Hampers",
  },
  // ── Valentine's Collection ──
  {
    id: "hamper-14",
    name: "Valentine's Big Box Chocolate Hamper",
    price: 699,
    description: "Classic Valentine's gift packed with premium chocolates in a beautiful gift box.",
    image: "Website_Images/Valentine's Big Box Chocolate Hamper.jpg",
    category: "Valentine's Collection",
    
  },
  {
    id: "hamper-15",
    name: "Valentine's Big Hamper",
    price: 999,
    description: "A grand Valentine's hamper with a rose, propose day card, teddy, Cadbury celebration, promise day card, Kisses, hug day card and a Valentine's card with a pendant.",
    image: "Website_Images/Valentine's Big Hamper (1).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-16",
    name: "Valentine's Big Hamper (Angle 2)",
    price: 999,
    image: "Website_Images/Valentine's Big Hamper (2).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-17",
    name: "Valentine's Card Hamper",
    price: 799,
    description: "Card-forward hamper with a romantic finish. Perfect for expressing your love.",
    image: "Website_Images/Valentine's Card Hamper.jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-18",
    name: "Valentine's Card Hamper (Angle 1)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (1).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-19",
    name: "Valentine's Card Hamper (Angle 2)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (2).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-20",
    name: "Valentine's Card Hamper (Angle 3)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (3).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-21",
    name: "Valentine's Card Hamper (Angle 4)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (4).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-22",
    name: "Valentine's Card Hamper (Angle 5)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (5).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-23",
    name: "Valentine's Card Hamper (Angle 6)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (6).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-24",
    name: "Valentine's Card Hamper (Angle 7)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (7).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-25",
    name: "Valentine's Card Hamper (Angle 8)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (8).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-26",
    name: "Valentine's Card Hamper (Angle 9)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (9).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-27",
    name: "Valentine's Card Hamper (Angle 10)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (10).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-28",
    name: "Valentine's Card Hamper (Angle 12)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (12).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-29",
    name: "Valentine's Card Hamper (Angle 13)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (13).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-30",
    name: "Valentine's Card Hamper (Angle 14)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (14).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-31",
    name: "Valentine's Card Hamper (Angle 15)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (15).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-32",
    name: "Valentine's Card Hamper (Angle 16)",
    price: 799,
    image: "Website_Images/Valentine's Card Hamper (16).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-33",
    name: "Valentine's Chocolate Hamper (with lights)",
    price: 349,
    description: "A romantic Valentine's hamper with 5-6 chocolate cards and 2-3 love cards in a glowing light setup.",
    image: "Website_Images/Valentine's Chocolate Hamper (with lights).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-34",
    name: "Valentine's Chocolate Hamper (with lights) (Angle 2)",
    price: 349,
    image: "Website_Images/Valentine's Chocolate Hamper (with lights) (2).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-35",
    name: "Valentine's Small Chocolate Hamper (with polaroids)",
    price: 349,
    description: "Compact Valentine's chocolate hamper with polaroid memories and sweets.",
    image: "Website_Images/Valentine's small Chocolate Hamper (with polaroids).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-36",
    name: "Valentine's Small Hamper (with Teddy)",
    price: 399,
    description: "Sweet small Valentine's hamper with a handmade rose, a teddy, a KitKat and a cute bow. Colors depend on availability.",
    image: "Website_Images/Valentine's small Hamper (with Teddy).jpg",
    category: "Valentine's Collection",
  },
  {
    id: "hamper-best-friend-sm",
    name: "Best Friend Hamper",
    price: 599,
    description: "A sweet and thoughtful hamper for your best friend. Currently out of stock — check back soon!",
    image: "Website_Images/For My Best Friend Hamper.png",
    category: "Occasion Hampers",
    outOfStock: true,
  },
  
 
];

const baseName = (name) => name.replace(/\s*\(Angle\s*\d+\)$/i, "").trim();

const mergeProductVariants = (entries) => {
    const merged = new Map();

    entries.forEach((entry) => {
        const key = `${entry.category}::${baseName(entry.name)}`;
        const existing = merged.get(key);

        if (!existing) {
            merged.set(key, {
                id: entry.id,
                name: baseName(entry.name),
                price: entry.price,
                category: entry.category,
                featured: Boolean(entry.featured),
                images: [entry.image],
            });
            return;
        }

        if (!existing.images.includes(entry.image)) {
            existing.images.push(entry.image);
        }
        if (entry.featured) {
            existing.featured = true;
        }
    });

    return Array.from(merged.values());
};

const products = mergeProductVariants(productEntries);

module.exports = {
    productEntries,
    products
};
